#**Advance ML Homework_4_ Naive Bayes Classifier**
Simulasi tugas Mesin Learning Lanjut dengan Python

Domisili
Rumah = 1
Kost = 2
Masjid = 3

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
from google.colab import files
upload = files.upload()

import io
dataset = pd.read_csv('IndexBahagia.csv')
dataset.head(10)

Saving IndexBahagia.csv to IndexBahagia.csv


IDInstance  Laptop  Domisili  UangSaku  Bahagia
0           1       1         1       105        0
1           2       0         2        90        0
2           3       0         1        75        0
3           4       1         2       110        1
4           5       0         3        90        1
5           6       0         2        70        0
6           7       1         3       200        0
7           8       0         1        65        1
8           9       0         2        75        0
9          10       0         1        90        1

In [2]:
X = dataset.iloc[:, [1, 2, 3]].values
print(X)

[[  1   1 105]
 [  0   2  90]
 [  0   1  75]
 [  1   2 110]
 [  0   3  90]
 [  0   2  70]
 [  1   3 200]
 [  0   1  65]
 [  0   2  75]
 [  0   1  90]]


In [3]:
y = dataset.iloc[:, -1].values
print(y)

[0 0 0 1 1 0 0 1 0 1]


In [17]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.8, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)

print(ac)

print(cm)

0.5
[[4 0]
 [4 0]]
